// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NomadBuddy00.Data;

#nullable disable

namespace NomadBuddy00.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201061827_buddysupportadditionalfields")]
    partial class buddysupportadditionalfields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NomadBuddy00.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("NomadBuddy00.Models.ActivityAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("BuddyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Compensation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsLeadBuddy")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("BuddyId");

                    b.ToTable("ActivityAssignments");
                });

            modelBuilder.Entity("NomadBuddy00.Models.ActivityReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("NomadId");

                    b.ToTable("ActivityReservations");
                });

            modelBuilder.Entity("NomadBuddy00.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NomadBuddy00.Models.Buddy", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Buddies");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("BuddySupports");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuddyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BuddySupportId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.HasIndex("BuddySupportId");

                    b.ToTable("BuddySupportAssignments");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuddyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BuddySupportSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.HasIndex("BuddySupportSessionId");

                    b.HasIndex("NomadId");

                    b.ToTable("BuddySupportRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuddySupportId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RejectedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuddySupportId");

                    b.HasIndex("NomadId");

                    b.ToTable("BuddySupportRequests");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuddyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BuddySupportRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OptionalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.HasIndex("BuddySupportRequestId");

                    b.HasIndex("NomadId");

                    b.ToTable("BuddySupportSessions");
                });

            modelBuilder.Entity("NomadBuddy00.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageInternetSpeedMbps")
                        .HasColumnType("float");

                    b.Property<double>("CostOfLiving")
                        .HasColumnType("float");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("HealthcareQuality")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCoworkingSpaces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityCostOfLivingRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetLevel")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Food")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Housing")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsMonthly")
                        .HasColumnType("bit");

                    b.Property<decimal>("Leisure")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Transport")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NomadId");

                    b.ToTable("CityCostOfLivingRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityEntertainmentRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("EventsFrequencyScore")
                        .HasColumnType("int");

                    b.Property<int>("NightlifeScore")
                        .HasColumnType("int");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YouthVibeScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NomadId");

                    b.ToTable("CityEntertainmentRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityHealthcareRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailabilityScore")
                        .HasColumnType("int");

                    b.Property<decimal>("AvgDoctorVisitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgInsuranceMonthlyCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NomadId");

                    b.ToTable("CityHealthcareRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityOverallRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NomadId");

                    b.ToTable("CityOverallRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CitySafetyRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("DaySafety")
                        .HasColumnType("int");

                    b.Property<bool>("FeltHarassed")
                        .HasColumnType("bit");

                    b.Property<int>("NightSafety")
                        .HasColumnType("int");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NomadId");

                    b.ToTable("CitySafetyRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CityTags");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityTagVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CityTagId")
                        .HasColumnType("int");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CityTagId");

                    b.HasIndex("NomadId");

                    b.ToTable("CityTagVotes");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityTransportRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppConvenienceScore")
                        .HasColumnType("int");

                    b.Property<int>("BikeFriendlyScore")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MotorbikeEaseScore")
                        .HasColumnType("int");

                    b.Property<int>("NightTransportScore")
                        .HasColumnType("int");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PublicTransportScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransportCostScore")
                        .HasColumnType("int");

                    b.Property<int>("WalkabilityScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NomadId");

                    b.ToTable("CityTransportRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CollabIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollabSpaceId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollabSpaceId");

                    b.ToTable("CollabIdeas");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CollabSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("NomadMatchId")
                        .HasColumnType("int");

                    b.Property<string>("SharedGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomadMatchId");

                    b.ToTable("CollabSpaces");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Continent")
                        .HasColumnType("int");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NomadBuddy00.Models.FriendsProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunFact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPartyAnimal")
                        .HasColumnType("bit");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NomadId")
                        .IsUnique();

                    b.ToTable("FriendsProfiles");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NetworkingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomadId")
                        .IsUnique();

                    b.ToTable("NetworkingProfiles");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Nomad", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CurrentCityId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentCountryId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int>("NomadType")
                        .HasColumnType("int");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SelectedMode")
                        .HasColumnType("int");

                    b.Property<int>("TravelBudget")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CurrentCityId");

                    b.HasIndex("CurrentCountryId");

                    b.HasIndex("NationalityId");

                    b.ToTable("Nomads");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadCompatibilityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("TargetNomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NomadId");

                    b.HasIndex("TargetNomadId");

                    b.ToTable("NomadCompatibilityScores");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomadId");

                    b.ToTable("NomadInterests");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LikerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LikerId");

                    b.HasIndex("TargetId");

                    b.ToTable("NomadLikes");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FinalMatchScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Nomad1Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nomad2Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nomad1Id");

                    b.HasIndex("Nomad2Id");

                    b.ToTable("NomadMatches");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TravelerPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomadId");

                    b.HasIndex("TravelerPreferenceId");

                    b.ToTable("NomadPreferences");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TravelerQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomadId");

                    b.HasIndex("TravelerQuestionId");

                    b.ToTable("TravelerAnswers");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TravelerPreferences");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelerTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelerTypeId");

                    b.ToTable("TravelerQuestions");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemType")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TravelerTypes");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerTypeScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TravelerTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomadId");

                    b.HasIndex("TravelerTypeId");

                    b.ToTable("TravelerTypeScores");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TripPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedByNomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("NomadMatchId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripPinStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("NomadMatchId");

                    b.ToTable("TripPins");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TripPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NomadId");

                    b.ToTable("TripPlans");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TripStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("VisaPolicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("TripPlanId");

                    b.HasIndex("VisaPolicyId");

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("NomadBuddy00.Models.VisaPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<int?>("AllowedStayDays")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedCostUSD")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisaFreePeriodDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NationalityId");

                    b.ToTable("VisaPolicies");
                });

            modelBuilder.Entity("TravelerPreferenceTravelerType", b =>
                {
                    b.Property<int>("SuggestedForTypesId")
                        .HasColumnType("int");

                    b.Property<int>("SuggestedPreferencesId")
                        .HasColumnType("int");

                    b.HasKey("SuggestedForTypesId", "SuggestedPreferencesId");

                    b.HasIndex("SuggestedPreferencesId");

                    b.ToTable("TravelerTypePreference", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NomadBuddy00.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NomadBuddy00.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NomadBuddy00.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NomadBuddy00.Models.Activity", b =>
                {
                    b.HasOne("NomadBuddy00.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("NomadBuddy00.Models.ActivityAssignment", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Activity", "Activity")
                        .WithMany("ActivityAssignments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Buddy", "Buddy")
                        .WithMany("ActivityAssignments")
                        .HasForeignKey("BuddyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Buddy");
                });

            modelBuilder.Entity("NomadBuddy00.Models.ActivityReservation", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Activity", "Activity")
                        .WithMany("Reservations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany("Reservations")
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.ApplicationUser", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Buddy", b =>
                {
                    b.HasOne("NomadBuddy00.Models.ApplicationUser", "User")
                        .WithOne("Buddy")
                        .HasForeignKey("NomadBuddy00.Models.Buddy", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupport", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NomadBuddy00.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportAssignment", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Buddy", "Buddy")
                        .WithMany("BuddySupportAssignments")
                        .HasForeignKey("BuddyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.BuddySupport", "BuddySupport")
                        .WithMany("BuddySupportAssignments")
                        .HasForeignKey("BuddySupportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buddy");

                    b.Navigation("BuddySupport");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportRating", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Buddy", "Buddy")
                        .WithMany()
                        .HasForeignKey("BuddyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.BuddySupportSession", "BuddySupportSession")
                        .WithMany()
                        .HasForeignKey("BuddySupportSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buddy");

                    b.Navigation("BuddySupportSession");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportRequest", b =>
                {
                    b.HasOne("NomadBuddy00.Models.BuddySupport", "BuddySupport")
                        .WithMany()
                        .HasForeignKey("BuddySupportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuddySupport");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupportSession", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Buddy", "Buddy")
                        .WithMany()
                        .HasForeignKey("BuddyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.BuddySupportRequest", "BuddySupportRequest")
                        .WithMany()
                        .HasForeignKey("BuddySupportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buddy");

                    b.Navigation("BuddySupportRequest");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.City", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityCostOfLivingRating", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany("CostRatings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityEntertainmentRating", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityHealthcareRating", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany("HealthcareRatings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityOverallRating", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany("Ratings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CitySafetyRating", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany("SafetyRatings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityTagVote", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany("TagVotes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.CityTag", "CityTag")
                        .WithMany("Votes")
                        .HasForeignKey("CityTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("CityTag");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityTransportRating", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany("TransportRatings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CollabIdea", b =>
                {
                    b.HasOne("NomadBuddy00.Models.CollabSpace", "CollabSpace")
                        .WithMany("Ideas")
                        .HasForeignKey("CollabSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollabSpace");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CollabSpace", b =>
                {
                    b.HasOne("NomadBuddy00.Models.NomadMatch", "NomadMatch")
                        .WithMany()
                        .HasForeignKey("NomadMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NomadMatch");
                });

            modelBuilder.Entity("NomadBuddy00.Models.FriendsProfile", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithOne("FriendsProfile")
                        .HasForeignKey("NomadBuddy00.Models.FriendsProfile", "NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NetworkingProfile", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithOne("NetworkingProfile")
                        .HasForeignKey("NomadBuddy00.Models.NetworkingProfile", "NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Nomad", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "CurrentCity")
                        .WithMany()
                        .HasForeignKey("CurrentCityId");

                    b.HasOne("NomadBuddy00.Models.Country", "CurrentCountry")
                        .WithMany()
                        .HasForeignKey("CurrentCountryId");

                    b.HasOne("NomadBuddy00.Models.Nationality", "Nationality")
                        .WithMany("Nomads")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.ApplicationUser", "User")
                        .WithOne("Nomad")
                        .HasForeignKey("NomadBuddy00.Models.Nomad", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentCity");

                    b.Navigation("CurrentCountry");

                    b.Navigation("Nationality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadCompatibilityScore", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "TargetNomad")
                        .WithMany()
                        .HasForeignKey("TargetNomadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Nomad");

                    b.Navigation("TargetNomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadInterest", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany("Interests")
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadLike", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Liker")
                        .WithMany()
                        .HasForeignKey("LikerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Liker");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadMatch", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad1")
                        .WithMany()
                        .HasForeignKey("Nomad1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad2")
                        .WithMany()
                        .HasForeignKey("Nomad2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Nomad1");

                    b.Navigation("Nomad2");
                });

            modelBuilder.Entity("NomadBuddy00.Models.NomadPreference", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany("Preferences")
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.TravelerPreference", "TravelerPreference")
                        .WithMany()
                        .HasForeignKey("TravelerPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomad");

                    b.Navigation("TravelerPreference");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerAnswer", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.TravelerQuestion", "TravelerQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("TravelerQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomad");

                    b.Navigation("TravelerQuestion");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerQuestion", b =>
                {
                    b.HasOne("NomadBuddy00.Models.TravelerType", "TravelerType")
                        .WithMany("Questions")
                        .HasForeignKey("TravelerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelerType");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerTypeScore", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.TravelerType", "TravelerType")
                        .WithMany("Scores")
                        .HasForeignKey("TravelerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomad");

                    b.Navigation("TravelerType");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TripPin", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId");

                    b.HasOne("NomadBuddy00.Models.NomadMatch", "NomadMatch")
                        .WithMany()
                        .HasForeignKey("NomadMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("NomadMatch");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TripPlan", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Nomad", "Nomad")
                        .WithMany()
                        .HasForeignKey("NomadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TripStop", b =>
                {
                    b.HasOne("NomadBuddy00.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("NomadBuddy00.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.TripPlan", "TripPlan")
                        .WithMany("TripStops")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.VisaPolicy", "VisaPolicy")
                        .WithMany()
                        .HasForeignKey("VisaPolicyId");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("TripPlan");

                    b.Navigation("VisaPolicy");
                });

            modelBuilder.Entity("NomadBuddy00.Models.VisaPolicy", b =>
                {
                    b.HasOne("NomadBuddy00.Models.Country", "Country")
                        .WithMany("VisaPolicies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.Nationality", "Nationality")
                        .WithMany("VisaPolicies")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("TravelerPreferenceTravelerType", b =>
                {
                    b.HasOne("NomadBuddy00.Models.TravelerType", null)
                        .WithMany()
                        .HasForeignKey("SuggestedForTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadBuddy00.Models.TravelerPreference", null)
                        .WithMany()
                        .HasForeignKey("SuggestedPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NomadBuddy00.Models.Activity", b =>
                {
                    b.Navigation("ActivityAssignments");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("NomadBuddy00.Models.ApplicationUser", b =>
                {
                    b.Navigation("Buddy");

                    b.Navigation("Nomad");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Buddy", b =>
                {
                    b.Navigation("ActivityAssignments");

                    b.Navigation("BuddySupportAssignments");
                });

            modelBuilder.Entity("NomadBuddy00.Models.BuddySupport", b =>
                {
                    b.Navigation("BuddySupportAssignments");
                });

            modelBuilder.Entity("NomadBuddy00.Models.City", b =>
                {
                    b.Navigation("CostRatings");

                    b.Navigation("HealthcareRatings");

                    b.Navigation("Ratings");

                    b.Navigation("SafetyRatings");

                    b.Navigation("TagVotes");

                    b.Navigation("TransportRatings");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CityTag", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("NomadBuddy00.Models.CollabSpace", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("VisaPolicies");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Nationality", b =>
                {
                    b.Navigation("Nomads");

                    b.Navigation("VisaPolicies");
                });

            modelBuilder.Entity("NomadBuddy00.Models.Nomad", b =>
                {
                    b.Navigation("FriendsProfile");

                    b.Navigation("Interests");

                    b.Navigation("NetworkingProfile");

                    b.Navigation("Preferences");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TravelerType", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("NomadBuddy00.Models.TripPlan", b =>
                {
                    b.Navigation("TripStops");
                });
#pragma warning restore 612, 618
        }
    }
}
